/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface StudentDisplay {
    'student': any;
  }
  interface StudentList {}
}

declare global {


  interface HTMLStudentDisplayElement extends Components.StudentDisplay, HTMLStencilElement {}
  var HTMLStudentDisplayElement: {
    prototype: HTMLStudentDisplayElement;
    new (): HTMLStudentDisplayElement;
  };

  interface HTMLStudentListElement extends Components.StudentList, HTMLStencilElement {}
  var HTMLStudentListElement: {
    prototype: HTMLStudentListElement;
    new (): HTMLStudentListElement;
  };
  interface HTMLElementTagNameMap {
    'student-display': HTMLStudentDisplayElement;
    'student-list': HTMLStudentListElement;
  }
}

declare namespace LocalJSX {
  interface StudentDisplay {
    'student'?: any;
  }
  interface StudentList {}

  interface IntrinsicElements {
    'student-display': StudentDisplay;
    'student-list': StudentList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'student-display': LocalJSX.StudentDisplay & JSXBase.HTMLAttributes<HTMLStudentDisplayElement>;
      'student-list': LocalJSX.StudentList & JSXBase.HTMLAttributes<HTMLStudentListElement>;
    }
  }
}


